# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovX7CBkiOuo1NLRAFKdsUDnWngIAICue
"""

!pip install -U langchain-google-genai langchain-community chromadb pypdf

!pip install langchain-google-genai langchain langchain-community chromadb pypdf google-generativeai sentence-transformers

import os
from dotenv import load_dotenv
import google.generativeai as genai
from google.colab import userdata, files
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import Chroma

from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

from langchain_community.embeddings import HuggingFaceEmbeddings

api_key = userdata.get('GOOGLE_API_KEY')
os.environ["GOOGLE_API_KEY"] = api_key
genai.configure(api_key=api_key)

print("\n--- Please upload your PDF ---")
uploaded = files.upload()
pdf_filename = list(uploaded.keys())[0]

#Build the RAG Pipeline
print(f"\n🔄 Processing '{pdf_filename}'...")
loader = PyPDFLoader(pdf_filename)
docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
splits = text_splitter.split_documents(docs)

#Using a local model
print("Initializing local embedding model (no API quota used)")
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# print("Saving chunks to vector database")
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings, collection_name="local_rag_store")
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

# Initialize Gemini LLM for answering questions
llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)

# Define the Prompt
system_prompt = (
    "You are an assistant for question-answering tasks. Use the following pieces "
    "of retrieved context to answer the question. If you don't know the answer, "
    "say that you don't know.\n\nContext:\n{context}"
)

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),
])

# Create the RAG Chains
question_answer_chain = create_stuff_documents_chain(llm, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

print("Gemini Bot is ready!")

# 5. Interaction Loop
print("\n--- Chat with your PDF (Type 'exit' to quit) ---")
while True:
    user_query = input("You: ")
    if user_query.lower() in ['exit', 'quit']:
        print("Goodbye!")
        break
    if not user_query.strip():
        continue

    # Invoke the chain and print the response
    response = rag_chain.invoke({"input": user_query})
    print(f"Bot: {response['answer']}\n")